export const data = {
  subTotal: '$8,800.00',
  tax: '$1,760.00',
  total: '$10,560.00',
  items: [
    {
      id: 1,
      title: 'Twitter Scraping',
      description: 'Inventing new ways to get twitter data.',
      tech: 'Python',
      details: 'https://github.com/tr1pwyr/tweetData',
      category: 'Data',
    },
    {
      id: 2,
      title: 'Headlin3s',
      description: 'Headlin3s Alternative News Headlines.',
      tech: 'Node / JS',
      details: 'https://headlin3s.com',
      category: 'Development',
    },
    {
      id: 3,
      title: 'Secure Network',
      description: 'Gateway to a secure network.',
      tech: 'Linux',
      details: 'https://github.com/tr1pwyr/tweetData',
      category: 'Security',
    },
    {
      id: 4,
      title: 'Vue Frontend',
      description: 'A Vue3 Frontend Template.',
      tech: 'Vue 3',
      details: 'https://front-end.us/',
      category: 'Development',
    },
    {
      id: 5,
      title: 'Ambiguous Redirect',
      description: 'AI Powered Blog.',
      tech: 'Python',
      details: 'https://ambiguousredirect.com/',
      category: 'Development',
    },
    {
      id: 6,
      title: 'Website Creation',
      description: 'The creation of this website.',
      tech: 'Vue 3',
      details: 'https://tr1pwyr.com/',
      category: 'Development',
    },
    {
      id: 7,
      title: 'Firebase to MongoDB',
      description: 'Migrating data from Firebase to MongoDB.',
      tech: 'MongoDB',
      details: 'https://tr1pwyr.com/',
      category: 'Data',
    },
  ],
}