export const projects = {
  items: [
    {
      id: 1,
      title: 'Twitter Scraping',
      description: 'Scraping GB of Twitter data.',
      tech: 'Python',
      details: 'https://github.com/tr1pwyr/tweetData',
      category: 'Data',
    },
    {
      id: 2,
      title: 'Headlin3s',
      description: 'Headlin3s Alternative News Headlines.',
      tech: 'Vue / Node',
      details: 'https://headlin3s.com',
      category: 'Development',
    },
    {
      id: 3,
      title: 'Secure Network',
      description: 'Setup Gateway to a secure network.',
      tech: 'Linux',
      details: 'https://github.com/tr1pwyr/tweetData',
      category: 'Security',
    },
    {
      id: 4,
      title: 'Front-End.us',
      description: 'A Vue3 Frontend Template.',
      tech: 'Vue 3',
      details: 'https://front-end.us/',
      category: 'Development',
    },
    {
      id: 5,
      title: '[wL] wLog.app',
      description: 'Towards a more perfect AI Powered Blog',
      tech: 'Javascript',
      details: 'https://wlog.app/',
      category: 'Development',
    },
    {
      id: 6,
      title: 'Website Creation',
      description: 'The creation of this website.',
      tech: 'Vue 3',
      details: 'https://tr1pwyr.com/',
      category: 'Development',
    },
    {
      id: 7,
      title: 'Firebase to MongoDB',
      description: 'Migrating data from Firebase to MongoDB.',
      tech: 'MongoDB',
      details: 'https://tr1pwyr.com/',
      category: 'Data',
    },
  ],
}